### ISSUE TITLE
Name of this library?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-library-next#1]
We had a semi-consensus on calling it scala-library-future, but the more I think about it, the more I think that the ambiguity with `scala.concurrent.Future` is bad news. It maybe isn't so bad on a screen, but when you say "scala library future" out loud, it's reallllly ambiguous.

For now I've named the repo "scala-library-next", but it can still be renamed, we aren't locked in until we actually publish the initial version.

Thoughts?

**Comment by NthPortal** [comment]
I see your point about the confusion with `s.c.Future`, and I'm fine with `scala-library-next`

**Comment by Ichoran** [comment]
Can we name it after some cool creature?  Apple got a lot of the cats, but they haven't done birds of prey yet!  We could name it Merlin or Peregrin or Osprey....

More seriously (equally seriously) we have to be careful about naming because things in the future become things in the present, which then become things in the past.  scala-library-next and scala-library-future are both bad names for things for an old version from years ago.

If we can come up with a descriptor that doesn't depend on when "now" is, that would be better.

**Comment by NthPortal** [comment]
as I see it, there's nothing stopping this library from containing features for the "next" scala-library even for future versions of scala-library. there may be some things that aren't fixable until 4.0 that it will be needed for, and even without that, it's possible we may want something with a shorter release cycle than scala-library (which, even after 3.1, I don't know how frequently it will release).

**Comment by SethTisue** [comment]
@oli-kitty on Valentines it sounded like you and your co-host were iffy on the name. care to weigh in here?

**Comment by SethTisue** [comment]
I think the concern about the relative nature of "next" will be addressed by bumping the major version.

We've been calling it "scala-library-next" in conversation for quite some time now and people seem okay with it, so especially in the absence of any strongly competing suggestion, I think this is settled.
